version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: trendhub
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: trendhub_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: admin-runner
    restart: always
    environment:
      - DATABASE_URL=postgresql://trendhub:your_password@postgres:5432/trendhub_db
      - NEXTAUTH_URL=https://admin.your-domain.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:3001
      - NEXTAUTH_SECRET=your-secret-key
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-runner
    container_name: trendhub-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001/api}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - admin
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data: