packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@vercel/speed-insights'
  - core-js-pure
  - esbuild
  - prisma
  - sharp

patchedDependencies:
  '@heroui/dom-animation@2.1.8-beta.2': patches/@heroui__dom-animation@2.1.8-beta.2.patch
