packages:
  - packages/*
  - apps/*
ignoredBuiltDependencies:
  - '@heroui/shared-utils'
  - '@swc/core'
  - '@vercel/speed-insights'
  - esbuild
  - framer-motion
  - next
  - react
  - react-dom
  - sharp
