packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - unrs-resolver
onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@vercel/speed-insights'
  - core-js-pure
  - esbuild
  - prisma
  - puppeteer
  - sharp
  - unrs-resolver
