import { heroui } from "@heroui/theme";
import { colors } from "./src/lib/colors";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "../../node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      container: {
        center: true,
        padding: "1rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)"],
        mono: ["var(--font-roboto)"],
        poppins: ["var(--font-poppins)"],
        "open-sans": ["var(--font-open-sans)"],
      },
      colors: {
        // 背景色
        "bg-primary": {
          light: colors.light.background.primary,
          dark: colors.dark.background.primary,
          DEFAULT: colors.light.background.primary,
        },
        "bg-secondary": {
          light: colors.light.background.secondary,
          dark: colors.dark.background.secondary,
          DEFAULT: colors.light.background.secondary,
        },
        "bg-tertiary": {
          light: colors.light.background.tertiary,
          dark: colors.dark.background.tertiary,
          DEFAULT: colors.light.background.tertiary,
        },
        // 文字颜色
        "text-primary": {
          light: colors.light.text.primary,
          dark: colors.dark.text.primary,
          DEFAULT: colors.light.text.primary,
        },
        "text-secondary": {
          light: colors.light.text.secondary,
          dark: colors.dark.text.secondary,
          DEFAULT: colors.light.text.secondary,
        },
        "text-tertiary": {
          light: colors.light.text.tertiary,
          dark: colors.dark.text.tertiary,
          DEFAULT: colors.light.text.tertiary,
        },
        // 边框颜色
        "border-primary": {
          light: colors.light.border.primary,
          dark: colors.dark.border.primary,
          DEFAULT: colors.light.border.primary,
        },
        "border-secondary": {
          light: colors.light.border.secondary,
          dark: colors.dark.border.secondary,
          DEFAULT: colors.light.border.secondary,
        },
        // 悬停颜色
        "hover-bg": {
          light: colors.light.hover.background,
          dark: colors.dark.hover.background,
          DEFAULT: colors.light.hover.background,
        },
        "hover-text": {
          light: colors.light.hover.text,
          dark: colors.dark.hover.text,
          DEFAULT: colors.light.hover.text,
        },
        // HeroUI 语义颜色 - 动态支持暗色模式
        primary: {
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-900)",
          DEFAULT: "var(--primary-500)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          50: "var(--secondary-50)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-900)",
          DEFAULT: "var(--secondary-500)",
          foreground: "var(--secondary-foreground)",
        },
        success: {
          50: "var(--success-50)",
          100: "var(--success-100)",
          200: "var(--success-200)",
          300: "var(--success-300)",
          400: "var(--success-400)",
          500: "var(--success-500)",
          600: "var(--success-600)",
          700: "var(--success-700)",
          800: "var(--success-800)",
          900: "var(--success-900)",
          DEFAULT: "var(--success-500)",
          foreground: "var(--success-foreground)",
        },
        warning: {
          50: "var(--warning-50)",
          100: "var(--warning-100)",
          200: "var(--warning-200)",
          300: "var(--warning-300)",
          400: "var(--warning-400)",
          500: "var(--warning-500)",
          600: "var(--warning-600)",
          700: "var(--warning-700)",
          800: "var(--warning-800)",
          900: "var(--warning-900)",
          DEFAULT: "var(--warning-500)",
          foreground: "var(--warning-foreground)",
        },
        danger: {
          50: "var(--danger-50)",
          100: "var(--danger-100)",
          200: "var(--danger-200)",
          300: "var(--danger-300)",
          400: "var(--danger-400)",
          500: "var(--danger-500)",
          600: "var(--danger-600)",
          700: "var(--danger-700)",
          800: "var(--danger-800)",
          900: "var(--danger-900)",
          DEFAULT: "var(--danger-500)",
          foreground: "var(--danger-foreground)",
        },
        default: {
          50: "var(--default-50)",
          100: "var(--default-100)",
          200: "var(--default-200)",
          300: "var(--default-300)",
          400: "var(--default-400)",
          500: "var(--default-500)",
          600: "var(--default-600)",
          700: "var(--default-700)",
          800: "var(--default-800)",
          900: "var(--default-900)",
          DEFAULT: "var(--default-500)",
          foreground: "var(--default-foreground)",
        },
      },
    },
  },
  darkMode: "class",
  plugins: [
    heroui({
      addCommonColors: true,
      themes: {
        light: {
          extend: true,
          colors: {
            background: colors.light.background.primary,
            foreground: colors.light.text.primary,
            primary: {
              50: colors.light.primary["50"],
              100: colors.light.primary["100"],
              200: colors.light.primary["200"],
              300: colors.light.primary["300"],
              400: colors.light.primary["400"],
              500: colors.light.primary["500"],
              600: colors.light.primary["600"],
              700: colors.light.primary["700"],
              800: colors.light.primary["800"],
              900: colors.light.primary["900"],
              DEFAULT: colors.light.primary["500"],
              foreground: "#FFFFFF",
            },
            secondary: {
              50: colors.light.secondary["50"],
              100: colors.light.secondary["100"],
              200: colors.light.secondary["200"],
              300: colors.light.secondary["300"],
              400: colors.light.secondary["400"],
              500: colors.light.secondary["500"],
              600: colors.light.secondary["600"],
              700: colors.light.secondary["700"],
              800: colors.light.secondary["800"],
              900: colors.light.secondary["900"],
              DEFAULT: colors.light.secondary["500"],
              foreground: "#FFFFFF",
            },
            success: {
              50: colors.light.success["50"],
              100: colors.light.success["100"],
              200: colors.light.success["200"],
              300: colors.light.success["300"],
              400: colors.light.success["400"],
              500: colors.light.success["500"],
              600: colors.light.success["600"],
              700: colors.light.success["700"],
              800: colors.light.success["800"],
              900: colors.light.success["900"],
              DEFAULT: colors.light.success["500"],
              foreground: "#FFFFFF",
            },
            warning: {
              50: colors.light.warning["50"],
              100: colors.light.warning["100"],
              200: colors.light.warning["200"],
              300: colors.light.warning["300"],
              400: colors.light.warning["400"],
              500: colors.light.warning["500"],
              600: colors.light.warning["600"],
              700: colors.light.warning["700"],
              800: colors.light.warning["800"],
              900: colors.light.warning["900"],
              DEFAULT: colors.light.warning["500"],
              foreground: "#FFFFFF",
            },
            danger: {
              50: colors.light.danger["50"],
              100: colors.light.danger["100"],
              200: colors.light.danger["200"],
              300: colors.light.danger["300"],
              400: colors.light.danger["400"],
              500: colors.light.danger["500"],
              600: colors.light.danger["600"],
              700: colors.light.danger["700"],
              800: colors.light.danger["800"],
              900: colors.light.danger["900"],
              DEFAULT: colors.light.danger["500"],
              foreground: "#FFFFFF",
            },
            default: {
              50: colors.light.default["50"],
              100: colors.light.default["100"],
              200: colors.light.default["200"],
              300: colors.light.default["300"],
              400: colors.light.default["400"],
              500: colors.light.default["500"],
              600: colors.light.default["600"],
              700: colors.light.default["700"],
              800: colors.light.default["800"],
              900: colors.light.default["900"],
              DEFAULT: colors.light.default["500"],
              foreground: "#FFFFFF",
            },
          },
        },
        dark: {
          extend: true,
          colors: {
            background: colors.dark.background.primary,
            foreground: colors.dark.text.primary,
            primary: {
              50: colors.dark.primary["50"],
              100: colors.dark.primary["100"],
              200: colors.dark.primary["200"],
              300: colors.dark.primary["300"],
              400: colors.dark.primary["400"],
              500: colors.dark.primary["500"],
              600: colors.dark.primary["600"],
              700: colors.dark.primary["700"],
              800: colors.dark.primary["800"],
              900: colors.dark.primary["900"],
              DEFAULT: colors.dark.primary["500"],
              foreground: "#000000",
            },
            secondary: {
              50: colors.dark.secondary["50"],
              100: colors.dark.secondary["100"],
              200: colors.dark.secondary["200"],
              300: colors.dark.secondary["300"],
              400: colors.dark.secondary["400"],
              500: colors.dark.secondary["500"],
              600: colors.dark.secondary["600"],
              700: colors.dark.secondary["700"],
              800: colors.dark.secondary["800"],
              900: colors.dark.secondary["900"],
              DEFAULT: colors.dark.secondary["500"],
              foreground: "#000000",
            },
            success: {
              50: colors.dark.success["50"],
              100: colors.dark.success["100"],
              200: colors.dark.success["200"],
              300: colors.dark.success["300"],
              400: colors.dark.success["400"],
              500: colors.dark.success["500"],
              600: colors.dark.success["600"],
              700: colors.dark.success["700"],
              800: colors.dark.success["800"],
              900: colors.dark.success["900"],
              DEFAULT: colors.dark.success["500"],
              foreground: "#000000",
            },
            warning: {
              50: colors.dark.warning["50"],
              100: colors.dark.warning["100"],
              200: colors.dark.warning["200"],
              300: colors.dark.warning["300"],
              400: colors.dark.warning["400"],
              500: colors.dark.warning["500"],
              600: colors.dark.warning["600"],
              700: colors.dark.warning["700"],
              800: colors.dark.warning["800"],
              900: colors.dark.warning["900"],
              DEFAULT: colors.dark.warning["500"],
              foreground: "#000000",
            },
            danger: {
              50: colors.dark.danger["50"],
              100: colors.dark.danger["100"],
              200: colors.dark.danger["200"],
              300: colors.dark.danger["300"],
              400: colors.dark.danger["400"],
              500: colors.dark.danger["500"],
              600: colors.dark.danger["600"],
              700: colors.dark.danger["700"],
              800: colors.dark.danger["800"],
              900: colors.dark.danger["900"],
              DEFAULT: colors.dark.danger["500"],
              foreground: "#000000",
            },
            default: {
              50: colors.dark.default["50"],
              100: colors.dark.default["100"],
              200: colors.dark.default["200"],
              300: colors.dark.default["300"],
              400: colors.dark.default["400"],
              500: colors.dark.default["500"],
              600: colors.dark.default["600"],
              700: colors.dark.default["700"],
              800: colors.dark.default["800"],
              900: colors.dark.default["900"],
              DEFAULT: colors.dark.default["500"],
              foreground: "#000000",
            },
          },
        },
      },
    }),
  ],
};
