name: Docker Build and Push

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_ADMIN: ${{ secrets.DOCKERHUB_USERNAME }}/trendhub-admin
  IMAGE_WEB: ${{ secrets.DOCKERHUB_USERNAME }}/trendhub-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送 admin 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: admin-runner
          push: true
          tags: |
            ${{ env.IMAGE_ADMIN }}:latest
            ${{ env.IMAGE_ADMIN }}:${{ github.sha }}

      - name: 构建并推送 web 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: web-runner
          push: true
          tags: |
            ${{ env.IMAGE_WEB }}:latest
            ${{ env.IMAGE_WEB }}:${{ github.sha }}

      # 如需自动部署到服务器，取消下方注释并补充 secrets
      # - name: 远程部署
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd /path/to/TrendHub
      #       docker compose pull
      #       docker compose up -d